services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: challenge_db
      POSTGRES_USER: challenge_user
      POSTGRES_PASSWORD: challenge_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/challenge_db
      SPRING_DATASOURCE_USERNAME: challenge_user
      SPRING_DATASOURCE_PASSWORD: challenge_password
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data: